name: code-style

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Code style

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: vendor/bin/pint --test
